language: node_js
node_js:
  - stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build_prod

local_dir: build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master